version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=todo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ENDPOINT=http://localstack:4566
      - S3_BUCKET=todo-files
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo
    volumes:
      - mysql-data:/var/lib/mysql
      - ../../migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - "6380:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0.0
    container_name: localstack
    ports:
      - "4570:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
      - HOSTNAME_EXTERNAL=localhost
      - LOCALSTACK_HOST=localhost
      - PERSISTENCE=1
      - S3_ENDPOINT_STRATEGY=path
      - DISABLE_S3_VIRTUAL_HOST=1
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - S3_SKIP_SIGNATURE_VALIDATION=1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/init"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  mysql-data:
  localstack-data:

networks:
  app-network:
    driver: bridge 